# =====================================================================
# GitHub Actions Workflow for Setting Up the Node.js Environment
# ---------------------------------------------------------------------
# Copyright 2025 © Astitv Singh <https://github.com/astitvsingh>
# SPDX-License-Identifier: MIT
# =====================================================================

name: "📦 Install Dependencies"
description: "Installs project dependencies using npm"

runs:
  using: "composite"
  steps:
    - name: 📦 Install Dependencies
      run: npm ci
      shell: bash
